.PHONY: help build test

help:
	@echo "targets: help, build, test"

build:
	@echo "Building the project takes some time..."
	@sleep 10
	@echo "Done!"

test: build
	@echo "Testing takes even more time..."
	@sleep 20
	@echo "Done!"
